name: Elixir CI

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: 1.5 # Define the elixir version [required]
        otp-version: 20.0 # Define the OTP version [required]
    - name: Install Dependencies
      run: mix deps.get
    - name: Compile project environments
      run: \
        MIX_ENV=test mix compile --warnings-as-errors
        MIX_ENV=dev mix compile --warnings-as-errors
        MIX_ENV=prod mix compile --warnings-as-errors
    - name: Check format
      run: mix format --check-formatted
    - name: Run credo
      run: mix credo --strict
    - name: Run dialyzer
      run: mix dialyzer --halt-exit-status
    - name: Run Tests
      run: mix test
